### PR TITLE
Update spec per SpanContext/Span/Baggage changes

### PR DESCRIPTION
**Pull request by bensigelman**
Per https://github.com/opentracing/opentracing.github.io/issues/106

### CODE REVIEW

**Comment by bensigelman** [comment]
cc @yurishkuro @cw1ess

Once this is merged we can close that https://github.com/opentracing/opentracing.github.io/issues/106 issue!

**Comment by yurishkuro** [comment]
:shipit:

**Comment by cwe1ss** [comment]
yep - looks good!

**Comment by bensigelman** [comment]
@cwe1ss sorry I misspelled your username above -- I took Deutsch in high school so I have no excuse (except for the `s/i/1/` :)

**Pull request merged**
