### PR TITLE
make companies logos wrap when there isn't enough space

### PR DESCRIPTION
**Pull request by reimertz**
fixes issues mentioned in  #133

### CODE REVIEW

**Comment by bensigelman** [comment]
Do you need to `npm publish`?

**Comment by reimertz** [comment]
There are no changes that this affect on the current state of the branch so I though it was unnecessary to do it. But it will be needed when we want to deploy the new logo. :)

**Comment by bensigelman** [comment]
As a best practice, I think we ought to mandate an`npm publish` with every merge. It will make diffs more predictable until we have a better solution.

Also, I think on mobile we already have too many logos for one line (even without the extra one).

**Comment by reimertz** [comment]
@bensigelman okay, i ran the production script now and pushed a new commit containing the changes.

**Comment by bensigelman** [comment]
thank you, @reimertz!

**Pull request merged**
