### PR TITLE
use the logo (and change the favicon)

### PR DESCRIPTION
**Pull request by bensigelman**

### CODE REVIEW

**Comment by bensigelman** [comment]
Desktop:

image


Chrome iPhone6 sim:

image


Chrome iPad sim:

image

**Comment by bensigelman** [comment]
Any/All: I just merged these logo changes because we have more important things to discuss :)

But if anyone wants to propose tweaks, obviously that's welcome.

**Comment by yurishkuro** [comment]
missing favicon

**Comment by bensigelman** [comment]
@yurishkuro 
image ??

**Comment by bensigelman** [comment]
Or, more to the point: 
image

**Comment by yurishkuro** [comment]
:+1:

**Pull request merged**
