### PR TITLE
save some redirects

### PR DESCRIPTION
**Pull request by bensigelman**
(already added the CNAME file to master... seems to work)

### CODE REVIEW

**Comment by bensigelman** [comment]
@yurishkuro @adriancole @slimsag github wants us to use a subdomain so I chose `docs.`. I'm assuming nobody really cares about this, so I'm merging. Easy to change later if we want!

**Comment by adriancole** [comment]
I'm fine with redirecting to docs, although I don't know what other root page we are expecting. Ex other sites like http://reactivex.io/ just use a path for docs, but yeah conserving bikeshed energy for naming convention :P

**Comment by bensigelman** [comment]
This was bugging me so I decided to "just fix it" while I still have the github pages domain stuff in my brain-cache. `opentracing.io` now hosts everything automatically, and the github-hosted site redirects there.

**Comment by bensigelman** [comment]
https://github.com/opentracing/opentracing.github.io/commit/21a75f6ea31bbddf9fc7ff1563a54047c0a66f2c
https://github.com/opentracing/opentracing.github.io/commit/3d837d1e1a8affafc1c1c725f7304c47ab74e18b

(and some DNS changes that can't be captured in git)

**Comment by yurishkuro** [comment]
I just tried http://opentracing.github.io/, it went to http://docs.opentracing.io/ and gave 404.

**Comment by bensigelman** [comment]
Weird, I tried it before and it worked... Can you try a hard reload?

On Saturday, January 9, 2016, Yuri Shkuro <notifications@github.com> wrote:

> I just tried http://opentracing.github.io/, it went to
> http://docs.opentracing.io/ and gave 404.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opentracing/opentracing.github.io/pull/12#issuecomment-170273652>
> .
>


-- 
Sent via mobile

**Comment by yurishkuro** [comment]
No, there isn't anything to reload as the website just redirects to `docs`.  I am seeing github docs recommending ALIAS record, or A records with IPs:

> If you are serving a top-level domain like example.com, you should have an ALIAS record pointing to username.github.io. If you cannot use an ALIAS record, you will need to create A records that point to 192.30.252.153 and 192.30.252.154

I see that you went with the latter

```
$ dig opentracing.io +nostats +nocomments +nocmd
;opentracing.io.                        IN      A
opentracing.io.         300     IN      A       192.30.252.153
opentracing.io.         300     IN      A       192.30.252.154
```

Maybe try the ALIAS instead?

**Comment by yurishkuro** [comment]
Actually, the redirect is likely happening on the github side, so another option is to alias docs subdomain to the top level domain, since that one is working fine.

**Comment by yurishkuro** [comment]
Wait, I just did a no-op update to CNAME file, and `docs` is no longer happening. We should be good.

**Comment by bensigelman** [comment]
Cool. And, "weird." I had checked all of this in the morning and stuff was
working fine for me. Maybe there was some funny caching thing happening on
my machine and masking the issues.

We'll never know, I guess :)

**Pull request merged**
